services:
  server:
    container_name: stockwatch-server
    env_file: .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
     
  client:
    container_name: stockwatch-client
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_ENDPOINT: ${RASE}
    ports:
      - "80:80"
      - "8001:8001"