# Compose being used on server hosting containers
services:
  server:
    image: ismailmohammad/stockwatch:server
    container_name: stockwatch-server
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
     
  client:
    image: ismailmohammad/stockwatch:client
    container_name: stockwatch-client
    volumes:
      - ./stockwatch/nginx:/etc/nginx/conf.d
      - ./stockwatch/certbot/conf:/etc/letsencrypt
      - ./stockwatch/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
    restart: always

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./stockwatch/certbot/conf:/etc/letsencrypt
      - ./stockwatch/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"