services:
  server:
    image: ismailmohammad/stockwatch:server
    container_name: stockwatch-server
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
     
  client:
    image: ismailmohammad/stockwatch:client
    container_name: stockwatch-client
    ports:
      - "80:80"
      - "443:443"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./stockwatch/certbot/conf:/etc/letsencrypt
      - ./stockwatch/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"